/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.timimakkonen.minesweeper.jni;

public class AndroidMinesweeperGame {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected AndroidMinesweeperGame(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AndroidMinesweeperGame obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        minesweeper_gameJNI.delete_AndroidMinesweeperGame(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public AndroidMinesweeperGame() {
    this(minesweeper_gameJNI.new_AndroidMinesweeperGame__SWIG_0(), true);
  }

  public AndroidMinesweeperGame(int gridHeight, int gridWidth, int numOfMines) {
    this(minesweeper_gameJNI.new_AndroidMinesweeperGame__SWIG_1(gridHeight, gridWidth, numOfMines), true);
  }

  public void reset(boolean keepCreatedMines) {
    minesweeper_gameJNI.AndroidMinesweeperGame_reset(swigCPtr, this, keepCreatedMines);
  }

  public void newGame(int gridHeight, int gridWidth, int numOfMines) {
    minesweeper_gameJNI.AndroidMinesweeperGame_newGame__SWIG_0(swigCPtr, this, gridHeight, gridWidth, numOfMines);
  }

  public void newGame(int gridHeight, int gridWidth, double proportionOfMines) {
    minesweeper_gameJNI.AndroidMinesweeperGame_newGame__SWIG_1(swigCPtr, this, gridHeight, gridWidth, proportionOfMines);
  }

  public void checkInputCoordinates(int x, int y) {
    minesweeper_gameJNI.AndroidMinesweeperGame_checkInputCoordinates(swigCPtr, this, x, y);
  }

  public void markInputCoordinates(int x, int y) {
    minesweeper_gameJNI.AndroidMinesweeperGame_markInputCoordinates(swigCPtr, this, x, y);
  }

  public boolean playerHasWon() {
    return minesweeper_gameJNI.AndroidMinesweeperGame_playerHasWon(swigCPtr, this);
  }

  public boolean playerHasLost() {
    return minesweeper_gameJNI.AndroidMinesweeperGame_playerHasLost(swigCPtr, this);
  }

  public int getGridHeight() {
    return minesweeper_gameJNI.AndroidMinesweeperGame_getGridHeight(swigCPtr, this);
  }

  public int getGridWidth() {
    return minesweeper_gameJNI.AndroidMinesweeperGame_getGridWidth(swigCPtr, this);
  }

  public int getNumOfMines() {
    return minesweeper_gameJNI.AndroidMinesweeperGame_getNumOfMines(swigCPtr, this);
  }

  public vector_int visualise() {
    return new vector_int(minesweeper_gameJNI.AndroidMinesweeperGame_visualise(swigCPtr, this), true);
  }

  public String serialise() {
    return minesweeper_gameJNI.AndroidMinesweeperGame_serialise(swigCPtr, this);
  }

  public boolean deserialise(String inStr) {
    return minesweeper_gameJNI.AndroidMinesweeperGame_deserialise(swigCPtr, this, inStr);
  }

  public static int maxNumOfMines(int gridHeight, int gridWidth) {
    return minesweeper_gameJNI.AndroidMinesweeperGame_maxNumOfMines(gridHeight, gridWidth);
  }

  public static double maxProportionOfMines(int gridHeight, int gridWidth) {
    return minesweeper_gameJNI.AndroidMinesweeperGame_maxProportionOfMines(gridHeight, gridWidth);
  }

  public static int minNumOfMines() {
    return minesweeper_gameJNI.AndroidMinesweeperGame_minNumOfMines();
  }

  public static double minProportionOfMines() {
    return minesweeper_gameJNI.AndroidMinesweeperGame_minProportionOfMines();
  }

}
