/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.timimakkonen.minesweeper.jni;

public class minesweeper_gameJNI {
  public final static native long new_vector_int__SWIG_0();
  public final static native long new_vector_int__SWIG_1(long jarg1, vector_int jarg1_);
  public final static native long vector_int_capacity(long jarg1, vector_int jarg1_);
  public final static native void vector_int_reserve(long jarg1, vector_int jarg1_, long jarg2);
  public final static native boolean vector_int_isEmpty(long jarg1, vector_int jarg1_);
  public final static native void vector_int_clear(long jarg1, vector_int jarg1_);
  public final static native long new_vector_int__SWIG_2(int jarg1, int jarg2);
  public final static native int vector_int_doSize(long jarg1, vector_int jarg1_);
  public final static native void vector_int_doAdd__SWIG_0(long jarg1, vector_int jarg1_, int jarg2);
  public final static native void vector_int_doAdd__SWIG_1(long jarg1, vector_int jarg1_, int jarg2, int jarg3);
  public final static native int vector_int_doRemove(long jarg1, vector_int jarg1_, int jarg2);
  public final static native int vector_int_doGet(long jarg1, vector_int jarg1_, int jarg2);
  public final static native int vector_int_doSet(long jarg1, vector_int jarg1_, int jarg2, int jarg3);
  public final static native void vector_int_doRemoveRange(long jarg1, vector_int jarg1_, int jarg2, int jarg3);
  public final static native void delete_vector_int(long jarg1);
  public final static native long new_AndroidMinesweeperGame__SWIG_0();
  public final static native long new_AndroidMinesweeperGame__SWIG_1(int jarg1, int jarg2, int jarg3);
  public final static native void AndroidMinesweeperGame_reset(long jarg1, AndroidMinesweeperGame jarg1_, boolean jarg2);
  public final static native void AndroidMinesweeperGame_newGame__SWIG_0(long jarg1, AndroidMinesweeperGame jarg1_, int jarg2, int jarg3, int jarg4);
  public final static native void AndroidMinesweeperGame_newGame__SWIG_1(long jarg1, AndroidMinesweeperGame jarg1_, int jarg2, int jarg3, double jarg4);
  public final static native void AndroidMinesweeperGame_checkInputCoordinates(long jarg1, AndroidMinesweeperGame jarg1_, int jarg2, int jarg3);
  public final static native void AndroidMinesweeperGame_markInputCoordinates(long jarg1, AndroidMinesweeperGame jarg1_, int jarg2, int jarg3);
  public final static native boolean AndroidMinesweeperGame_playerHasWon(long jarg1, AndroidMinesweeperGame jarg1_);
  public final static native boolean AndroidMinesweeperGame_playerHasLost(long jarg1, AndroidMinesweeperGame jarg1_);
  public final static native int AndroidMinesweeperGame_getGridHeight(long jarg1, AndroidMinesweeperGame jarg1_);
  public final static native int AndroidMinesweeperGame_getGridWidth(long jarg1, AndroidMinesweeperGame jarg1_);
  public final static native int AndroidMinesweeperGame_getNumOfMines(long jarg1, AndroidMinesweeperGame jarg1_);
  public final static native long AndroidMinesweeperGame_visualise(long jarg1, AndroidMinesweeperGame jarg1_);
  public final static native long AndroidMinesweeperGame_visualiseSolution(long jarg1, AndroidMinesweeperGame jarg1_);
  public final static native String AndroidMinesweeperGame_serialise(long jarg1, AndroidMinesweeperGame jarg1_);
  public final static native boolean AndroidMinesweeperGame_deserialise(long jarg1, AndroidMinesweeperGame jarg1_, String jarg2);
  public final static native int AndroidMinesweeperGame_maxNumOfMines(int jarg1, int jarg2);
  public final static native double AndroidMinesweeperGame_maxProportionOfMines(int jarg1, int jarg2);
  public final static native int AndroidMinesweeperGame_minNumOfMines();
  public final static native double AndroidMinesweeperGame_minProportionOfMines();
  public final static native void delete_AndroidMinesweeperGame(long jarg1);
}
