/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.timimakkonen.minesweeper.jni;

public class vector_int extends java.util.AbstractList<Integer> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected vector_int(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(vector_int obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        minesweeper_gameJNI.delete_vector_int(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public vector_int(int[] initialElements) {
    this();
    reserve(initialElements.length);

    for (int element : initialElements) {
      add(element);
    }
  }

  public vector_int(Iterable<Integer> initialElements) {
    this();
    for (int element : initialElements) {
      add(element);
    }
  }

  public Integer get(int index) {
    return doGet(index);
  }

  public Integer set(int index, Integer e) {
    return doSet(index, e);
  }

  public boolean add(Integer e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, Integer e) {
    modCount++;
    doAdd(index, e);
  }

  public Integer remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public vector_int() {
    this(minesweeper_gameJNI.new_vector_int__SWIG_0(), true);
  }

  public vector_int(vector_int other) {
    this(minesweeper_gameJNI.new_vector_int__SWIG_1(vector_int.getCPtr(other), other), true);
  }

  public long capacity() {
    return minesweeper_gameJNI.vector_int_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    minesweeper_gameJNI.vector_int_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return minesweeper_gameJNI.vector_int_isEmpty(swigCPtr, this);
  }

  public void clear() {
    minesweeper_gameJNI.vector_int_clear(swigCPtr, this);
  }

  public vector_int(int count, int value) {
    this(minesweeper_gameJNI.new_vector_int__SWIG_2(count, value), true);
  }

  private int doSize() {
    return minesweeper_gameJNI.vector_int_doSize(swigCPtr, this);
  }

  private void doAdd(int x) {
    minesweeper_gameJNI.vector_int_doAdd__SWIG_0(swigCPtr, this, x);
  }

  private void doAdd(int index, int x) {
    minesweeper_gameJNI.vector_int_doAdd__SWIG_1(swigCPtr, this, index, x);
  }

  private int doRemove(int index) {
    return minesweeper_gameJNI.vector_int_doRemove(swigCPtr, this, index);
  }

  private int doGet(int index) {
    return minesweeper_gameJNI.vector_int_doGet(swigCPtr, this, index);
  }

  private int doSet(int index, int val) {
    return minesweeper_gameJNI.vector_int_doSet(swigCPtr, this, index, val);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    minesweeper_gameJNI.vector_int_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
